[package]
name = "deencode-fcgi"
version = "0.1.0"
authors = ["cigix <cigix@cigix.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
fastcgi = "1.0"
serde_json = "1.0.57"
